person:
  #单引号会将'/'作为字符串输出  双引号会将/n 作为换行输出
  #双引号不会转义 单引号会转义
#  userName: 'zhangsan'
  boss: true
  birth: 2019/12/9
  age: 18
#  insterests: [篮球，足球]
  interests:
    - 篮球
    - 足球
    - 18
  animal: [阿猫,阿狗]
#  score:
#    english: 80
#    math: 90
  score: {english: 80,math: 90}
  salarys:
    - 9999.98
    - 9999.99
  pet:
    name: 阿狗
    weight: 99.99
  allPets:
    sick:
      - {name: 阿狗,weight: 99.99}
      - name: 阿猫
        weight: 88.88
      - name: 啊虫
        weight: 77.77
    health:
      - {name: 阿华,weight: 199.99}
      - {name: 阿明,weight: 199.99}
  user-name: zhangsan